"""
RoleTemplateEngine — generate system prompts from role character definition.

A role's character is described by two complementary schemas:

  Nine Chapter dimensions (scored 0–100):
    core_values, cognitive_style, social_orientation,
    emotional_reaction, adaptability

  Character fields (free-text, from AgencyAgentsBridge or direct authoring):
    name, purpose, archetype, system_prompt (legacy), dimensions[].summary

The engine assembles the CHARACTER portion of the system prompt.
It never includes tool or capability names — those are injected separately
by the executor via CapabilityResolver + build_capability_summary.

Prompt stack (generated by this engine):
  1. Identity block        — who the agent is
  2. Character narrative   — purpose, values, cognitive/social style
  3. Behavioral directives — Nine Chapter → concrete behavioral rules
  4. Task context          — success patterns + escalation rules (if defined)
  5. Capability summary    — what categories this role can use

Legacy compatibility:
  If role.get("system_prompt") exists it is used as the identity/character
  block (replacing #1 and #2).  Nine Chapter overlay and task context are
  always applied on top regardless.

Growth path:
  When a role accumulates enough task reflections in memory, the ORIENT
  phase surfaces them into the first user message — the template itself
  stays stable.  Character evolves through memory, not prompt re-authoring.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from app.scheduler.ninechapter import (
    build_behavioral_overlay,
    build_capability_summary,
    build_task_context,
)


class RoleTemplateEngine:
    """
    Assemble the character portion of an agent's system prompt.

    Usage
    -----
        engine = RoleTemplateEngine()
        character_block = engine.build(role)

    The returned string is slotted into the full system prompt by the executor:

        system_prompt = (
            mode_overlay
            + runtime_context
            + engine.build(role)       ← this
            + "\n\n---\n\n"
            + workflow_prompt
        )
    """

    def build(self, role: Dict[str, Any]) -> str:
        """
        Return the full character block for a role.
        Returns "" if role is None or empty.
        """
        if not role:
            return ""

        parts: List[str] = []

        # -- Identity / character narrative --
        identity = self._build_identity(role)
        if identity:
            parts.append(identity)

        # -- Nine Chapter behavioral directives --
        behavioral = build_behavioral_overlay(role)
        if behavioral:
            parts.append(behavioral)

        # -- Task context (success patterns + escalation rules) --
        task_ctx = build_task_context(role)
        if task_ctx:
            parts.append(task_ctx)

        # -- Capability summary --
        cap_summary = build_capability_summary(role)
        if cap_summary:
            parts.append(cap_summary)

        return "".join(parts)

    # ------------------------------------------------------------------
    # Identity / character narrative
    # ------------------------------------------------------------------

    def _build_identity(self, role: Dict[str, Any]) -> str:
        """
        Build the identity + character narrative block.

        Priority:
          1. role.get("system_prompt")  — legacy free-text (most common today)
          2. Structured generation from dimensions + purpose + archetype
        """
        # Legacy path — most roles still carry a hand-authored system_prompt
        legacy = (role.get("system_prompt") or "").strip()
        if legacy:
            return legacy + "\n\n"

        # Structured generation path (roles without a static system_prompt)
        return self._generate_from_dimensions(role)

    def _generate_from_dimensions(self, role: Dict[str, Any]) -> str:
        """
        Generate identity + character narrative from structured role fields.

        Used when role has no static system_prompt.  Produces a consistent,
        character-first description that never mentions tools or capabilities.
        """
        name = role.get("name") or role.get("id") or "Assistant"
        archetype = role.get("archetype", "").replace("_", " ")
        purpose = (role.get("purpose") or "").strip()
        dims = role.get("dimensions") or {}

        lines: List[str] = [f"You are {name}."]

        if archetype:
            lines.append(f"Archetype: {archetype}.")

        if purpose:
            lines.append(f"\n## Purpose\n{purpose}")

        # Pull dimension summaries as character traits
        trait_map = {
            "core_values":       "## Values",
            "cognitive_style":   "## How you think",
            "social_orientation":"## How you communicate",
            "emotional_reaction":"## How you respond under pressure",
            "adaptability":      "## How you handle change",
        }
        for dim_key, header in trait_map.items():
            entry = dims.get(dim_key)
            if not entry:
                continue
            summary = ""
            if isinstance(entry, dict):
                summary = (entry.get("summary") or "").strip()
            elif isinstance(entry, str):
                summary = entry.strip()
            if summary:
                lines.append(f"\n{header}\n{summary}")

        return "\n".join(lines) + "\n\n"
