#!/usr/bin/env python3
"""Plugin SDK CLI: scaffold and validate module plugins."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


def _slugify(name: str) -> str:
    slug = re.sub(r"[^a-z0-9_\\-]+", "-", name.lower()).strip("-")
    return slug or "plugin"


def _scaffold(args: argparse.Namespace) -> int:
    plugin_name = _slugify(args.name)
    provider_type = args.provider_type
    contract_version = args.contract_version
    version = args.version
    root = Path(args.output_dir).resolve() / plugin_name
    src_pkg = plugin_name.replace("-", "_")

    if root.exists() and any(root.iterdir()) and not args.force:
        print(f"[error] target exists and is not empty: {root}")
        print("Use --force to overwrite generated files where possible.")
        return 2

    (root / "src" / src_pkg).mkdir(parents=True, exist_ok=True)
    (root / "tests").mkdir(parents=True, exist_ok=True)

    class_name = "PluginProvider"
    entry_point = f"{src_pkg}.provider.{class_name}"
    module_json = {
        "name": plugin_name,
        "version": version,
        "provider_type": provider_type,
        "entry_point": entry_point,
        "contract_version": contract_version,
        "description": f"{provider_type} plugin scaffold for {plugin_name}",
        "capabilities": {},
    }
    (root / "module.json").write_text(
        json.dumps(module_json, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    provider_py = f'''"""Scaffold provider for {plugin_name}."""\n\nclass {class_name}:\n    """Implement the {provider_type} provider contract in your project."""\n\n    pass\n'''
    (root / "src" / src_pkg / "provider.py").write_text(provider_py, encoding="utf-8")
    (root / "src" / src_pkg / "__init__.py").write_text("", encoding="utf-8")
    (root / "README.md").write_text(
        f"# {plugin_name}\n\nGenerated by `scripts/plugin_sdk.py scaffold`.\n\n"
        "Next steps:\n"
        "1. Implement provider contract in `src/*/provider.py`.\n"
        "2. Run `python3 scripts/plugin_sdk.py validate --path <plugin-dir>`.\n"
        "3. Add conformance tests for your provider.\n",
        encoding="utf-8",
    )
    print(str(root))
    return 0


def _validate(args: argparse.Namespace) -> int:
    root = Path(args.path).resolve()
    module_path = root / "module.json"
    errors: list[str] = []

    if not module_path.exists():
        errors.append("missing module.json")
    else:
        try:
            data = json.loads(module_path.read_text(encoding="utf-8"))
        except Exception as exc:
            errors.append(f"invalid module.json: {exc}")
            data = None

        if isinstance(data, dict):
            required = ["name", "version", "provider_type", "entry_point", "contract_version"]
            for key in required:
                if key not in data or not str(data[key]).strip():
                    errors.append(f"module.json missing required key: {key}")
            ep = str(data.get("entry_point", ""))
            if "." not in ep:
                errors.append("entry_point must look like 'pkg.module.ClassName'")
            provider_type = str(data.get("provider_type", ""))
            if provider_type not in {"memory", "dream", "persona", "growth", "skill"}:
                errors.append(
                    "provider_type must be one of: memory,dream,persona,growth,skill"
                )

    src_dir = root / "src"
    if not src_dir.exists():
        errors.append("missing src/ directory")

    if errors:
        print("[invalid]")
        for e in errors:
            print(f"- {e}")
        return 2

    print("[ok] plugin manifest validated")
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Plugin SDK helper (scaffold + validate).")
    sub = p.add_subparsers(dest="cmd", required=True)

    sc = sub.add_parser("scaffold", help="Generate a plugin scaffold.")
    sc.add_argument("--name", required=True, help="Plugin name (e.g. my-memory-plugin)")
    sc.add_argument("--provider-type", required=True, choices=["memory", "dream", "persona", "growth", "skill"])
    sc.add_argument("--contract-version", default="1.0")
    sc.add_argument("--version", default="0.1.0")
    sc.add_argument("--output-dir", default="plugins")
    sc.add_argument("--force", action="store_true")
    sc.set_defaults(func=_scaffold)

    vd = sub.add_parser("validate", help="Validate a plugin manifest/package layout.")
    vd.add_argument("--path", required=True, help="Path to plugin root")
    vd.set_defaults(func=_validate)

    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
