#!/bin/bash
# MoJoAssistant Interactive CLI Launcher
# Auto-generated by install_mojo.py

echo "Starting MoJoAssistant Interactive CLI..."
echo ""

# Activate virtual environment
source venv/bin/activate

# Run interactive CLI with setup mode
python "$(dirname "$0")/../app/interactive-cli.py" --setup
